version: 2
updates:

  - package-ecosystem: "gomod"
    directory: "/providers/v1/akeyless"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10

  - package-ecosystem: docker
    directory: /e2e
    schedule:
      interval: weekly
    open-pull-requests-limit: 10

  - package-ecosystem: docker
    directory: /hack/api-docs
    schedule:
      interval: weekly
    open-pull-requests-limit: 10

  - package-ecosystem: pip
    directory: /hack/api-docs
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
