apiVersion: secrets.akeyless.io/v1alpha1
kind: AkeylessDynamicSecret
metadata:
  name: db-credentials
spec:
  storeRef:
    name: akeyless-store
    kind: AkeylessSecretStore
  path: /dynamic-secret/prod-db
  type: Dynamic
  secretKey: password
  syncPolicy: OnRemoteChange
  syncInterval: 1m
  target:
    name: db-credentials
  rolloutRestartTargets:
    - kind: Deployment
      name: api-server
