apiVersion: secrets.akeyless.io/v1alpha1
kind: AkeylessSecretStore
metadata:
  name: akeyless
spec:
  akeylessGWApiURL: "https://api.akeyless.io"
  auth:
    secretRef:
      accessID:
        name: akeyless-creds
        key: accessId
      accessType:
        name: akeyless-creds
        key: accessType
      accessTypeParam:
        name: akeyless-creds
        key: accessTypeParam
---
apiVersion: secrets.akeyless.io/v1alpha1
kind: AkeylessSecret
metadata:
  name: app-secret
spec:
  storeRef:
    name: akeyless
    kind: AkeylessSecretStore
  syncPolicy: OnRemoteChange
  syncInterval: 5m
  target:
    name: app-secret
    creationPolicy: Owner
  rolloutRestartTargets:
    - kind: Deployment
      name: myapp
  data:
    - secretKey: password
      remoteRef:
        key: /path/to/secret
